name: flutter_easy
description: A Easy Flutter application for start

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 本地存储、收藏功能
  shared_preferences: ^0.4.3
  # 异步处理
#  synchronized: ^2.1.0
  synchronized: ^1.5.1

  # json字符串处理
  json_serializable: ^2.0.0
  # toast处理
  fluttertoast: ^3.0.1
  #网络请求
  # https://github.com/flutterchina/dio
  dio: ^2.1.0

  #判断网络连接
  connectivity: ^0.4.2
  #eventbus
  event_bus:  ^1.0.3

  #flux框架
  flutter_redux: ^0.5.3
  #rx框架
  rxdart: ^0.21.0

  #网络图片加载
  cached_network_image: ^0.5.0+1
  flutter_cache_manager: ^0.2.0+1

  #router 页面路由跳转框架
  fluro: ^1.3.4

  # https://github.com/peng8350/flutter_pulltorefresh
  # 下拉刷新
  pull_to_refresh: ^1.2.0

  #语言国际化
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages


  #图片要在此处注册
  assets:
    - static/images/logo.png
    - static/images/welcome.png
    - static/images/default_img.png
    - static/images/app_welcome.png
    - static/images/flash_icon.png

    - static/images/ic_home.png
    - static/images/ic_home_pre.png
    - static/images/ic_order.png
    - static/images/ic_order_pre.png
    - static/images/ic_mine.png
    - static/images/ic_mine_pre.png
    - static/images/ic_minebg.png
    - static/images/ic_mine_userlogo.png
    - static/images/ic_tele.png
    - static/images/ic_login_title.png
    - static/images/ic_phone.png
    - static/images/ic_idcode.png
    - static/images/ic_checkbox_checked.png
    - static/images/ic_checkbox_normal.png
    - static/images/ic_banner.png

    - static/images/ic_home_buttom_left.png
    - static/images/ic_home_buttom_right.png

    - static/images/ic_tag1.png
    - static/images/ic_tag2.png
    - static/images/ic_tag3.png

    - static/images/ic_authent_idup.png
    - static/images/ic_authent_iddown.png
    - static/images/ic_authent_live.png

  fonts:
    - family: wxcIconFont
      fonts:
        - asset: static/font/iconfont.ttf